### ISSUE TITLE
Error when attempting to export k1 mesh rigged to k2 bones

### ISSUE THREAD

**Issue by reavt** [theturboturnip/yk_gmd_io#4]
Traceback (most recent call last):
  File "C:\Users\jenni\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\yk_gmd_blender\blender\export\gmd_exporter.py", line 113, in execute
    error_reporter)
  File "C:\Users\jenni\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\yk_gmd_blender\yk_gmd\v2\io.py", line 159, in write_abstract_scene_out
    file_data = pack_abstract_scene(version_props, file_is_big_endian, vertices_are_big_endian, scene, error_reporter)
  File "C:\Users\jenni\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\yk_gmd_blender\yk_gmd\v2\io.py", line 122, in pack_abstract_scene
    file_data = pack_abstract_contents_Dragon(version_props, file_is_big_endian, vertices_are_big_endian, scene, error_reporter)
  File "C:\Users\jenni\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\yk_gmd_blender\yk_gmd\v2\converters\dragon\from_abstract.py", line 285, in pack_abstract_contents_Dragon
    material_arr.append(gmd_material.port_to_version(version_properties.major_version).origin_data)
AttributeError: 'NoneType' object has no attribute 'origin_data'

location: <unknown location>:-1

**Comment by theturboturnip** [comment]
This should be fixed with v0.2.1
