### ISSUE TITLE
ImportError: attempted relative import with no known parent package

### ISSUE THREAD

**Issue by zyugyzarc** [theturboturnip/yk_gmd_io#64]
I get this when I try to enable the `yk_gmd_io` addon in blender, right after installing it (through `yk_gmd_io.zip`, v0.4.1).
```
Traceback (most recent call last):
  File "<somepath>/blender-3.5.0-alpha/3.5/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "<somepath>/blender/3.5/scripts/addons/yk_gmd_blender\__init__.py", line 29, in <module>
    from .blender.addon import *
ImportError: attempted relative import with no known parent package
```
Tried it on Blender 3.2, 3.3, 3.4 and 3.5 (alpha) - all failed with the same error.
Also I'm on linux if that matters (it shouldn't, hopefully)

**Comment by zyugyzarc** [comment]
update: this tool seems to be windows-only

**Comment by WaraiOtoko** [comment]
Any word on a solution yet?
v0.5.0 with Blender 4.0 still has this issue.

**Comment by dsinkerii** [comment]
> Any word on a solution yet? v0.5.0 with Blender 4.0 still has this issue.

Here's how i fixed it:
(steam)
1. Go to blender properties
2. Go to `Compatibility`, check `Force the use of a specific Steam Play compatibility tool`
3. Use any proton version (in my example Experimantal)
4. Update blender (this will reset your current workspace, upon reverting to your old version will be back)
5. Import the addon
If you use blender outside steam, use the official .exe from blender using wine

![image](https://github.com/theturboturnip/yk_gmd_io/assets/104655906/a017da37-99e8-4161-9599-ab5b52a4138f)
